version: 0.2

phases:
    install:
        commands:
            # install node 12
            - curl -sL https://deb.nodesource.com/setup_lts.x | bash -
            - apt-get install -y nodejs
    pre_build:
        commands:
            # install dependencies
            - npm install

    build:
        commands:
            # build project
            - npm run build

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist